### ISSUE TITLE
Your OneBusAway component for Home Assistant

### ISSUE THREAD

**Issue by RichardA1** [Spacetech/home-assistant-config#1]
I have been looking for something like this for quite a while. I loaded your code into my HASSio install and it is not working for some reason. Any chance you are looking to update it or submit it for official approval?

I just want to work my bus times into my automatons.

Thanks,
Richard A

**Comment by RichardA1** [comment]
This is the error that poped up in the HA log.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/onebusaway/sensor.py", line 128, in async_setup_platform
    stop_info_data = yield from OneBusAway.async_call_api(hass, stop_info_url, 'async_setup_platform')
  File "/config/custom_components/onebusaway/sensor.py", line 230, in async_call_api
    response_object = response.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Spacetech** [comment]
The component is up to date, it works for me.
Do you know what url it's calling when it gets that error? Sounds like the response isn't valid json. Double check the stop / route id you're using.

**Comment by RichardA1** [comment]
I did get it to work recently and it works well. There are a few things that would be helpful like showing the number of minutes before the next bus comes rather than the time it will arrive. Also, would it be possible to show data for the buses after the one coming next? I know that the API usually lists the next 2 to 3 busses.

I am trying to create an automation that changes a light panel near my door to green if I have time to make the next bus, yellow if I need to move to catch it, or red if I need to just wait for the next one.

I am very new to making components for HA or I would just jump in and make those changes myself.
